### ISSUE TITLE
VMamba链接失效

### ISSUE THREAD

**Issue by hustcselwb** [yyh-rain-song/ReMamber#1]

**Comment by yyh-rain-song** [comment]
https://drive.google.com/file/d/1O9P6XLuWtUxFa70vwrYCRVedRAFutczV/view?usp=sharing
我们自己上传了一个google drive的备份，感谢关注~

**Comment by yyh-rain-song** [comment]
https://drive.google.com/file/d/1O9P6XLuWtUxFa70vwrYCRVedRAFutczV/view?usp=sharing
我们自己上传了一个google drive的备份，感谢关注~
