### ISSUE TITLE
Question about data splitting and reproducing the experiment

### ISSUE THREAD

**Issue by HeeseongEom** [yyh-rain-song/ReMamber#5]
First of all, thank you for sharing your impressive research. I'm currently following your work, and I have a question regarding how the dataset is split for training and evaluation, especially since this is my first time working with the MSCOCO dataset.

From inspecting the code, it looks like the refer.py file uses the unc.p file for data splitting. However, with the refcoco dataset, I notice that during training, the code seems to perform two test evaluations per epoch. In your paper’s results table, you report the performance on val, testA, and testB for refcoco, and I’m trying to figure out which of the two test evaluations in the code correspond to those splits. I suspect that the two tests might correspond to testA and testB. If so, how would I check or measure the val performance?

Lastly, I’d also like to confirm whether, for the other datasets, the default settings in your code replicate the exact results (val / test splits) published in your paper.

Thank you very much in advance.

**Comment by yyh-rain-song** [comment]
The code does not contain evaluation on 'testA/B' split for simplicity. We only calculate result on 'val' split during training process for best checkpoint selection. To get 'testA/B' result, we resume the checkpoint and run another test script. 
- How to get val/testA/B result?
The script `main.py` offers an argument `--eval`, which allows a quick evaluation on 'val' split. To get result on 'testA/B' split, you need to modify the argument passed to `build_dataset` function in L149 like:
`dataset_val = build_dataset(is_train=False, args=args, split='testA')`

- About two test evaluations per epoch
That's the val result with current training model and model applied EMA update (which is usually slightly better)

**Comment by HeeseongEom** [comment]
Now I got it!
Thank you for your kind reply :)
